In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5504, 1544, 1350, 2400],
 [5504, 1544, 1350, 6480],
 [5504, 7547, 1350, 1900],
 [5922, 1085, 1002, 1954, 7354],
 [5922, 1085, 1002, 1954, 1012],
 [8815, 5504, 4057, 1350, 707],
 [8969, 5649, 9730, 1954]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5504 1544 1350 2400]
 [   0    0    0    0 5504 1544 1350 6480]
 [   0    0    0    0 5504 7547 1350 1900]
 [   0    0    0 5922 1085 1002 1954 7354]
 [   0    0    0 5922 1085 1002 1954 1012]
 [   0    0    0 8815 5504 4057 1350  707]
 [   0    0    0    0 8969 5649 9730 1954]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\ML\revise_ANN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step


array([[[-1.5594851e-02,  8.0844983e-03,  4.3571446e-02,  3.1632129e-02,
         -4.0844679e-02, -2.6517451e-02, -2.6639784e-02,  8.2488656e-03,
         -2.0312537e-02, -1.1454225e-02],
        [-1.5594851e-02,  8.0844983e-03,  4.3571446e-02,  3.1632129e-02,
         -4.0844679e-02, -2.6517451e-02, -2.6639784e-02,  8.2488656e-03,
         -2.0312537e-02, -1.1454225e-02],
        [-1.5594851e-02,  8.0844983e-03,  4.3571446e-02,  3.1632129e-02,
         -4.0844679e-02, -2.6517451e-02, -2.6639784e-02,  8.2488656e-03,
         -2.0312537e-02, -1.1454225e-02],
        [-1.5594851e-02,  8.0844983e-03,  4.3571446e-02,  3.1632129e-02,
         -4.0844679e-02, -2.6517451e-02, -2.6639784e-02,  8.2488656e-03,
         -2.0312537e-02, -1.1454225e-02],
        [ 4.4000935e-02,  4.0249672e-02,  1.6453791e-02, -1.0190643e-02,
          4.5857579e-04, -4.1169040e-03, -4.5813322e-03, -1.9774020e-02,
         -4.8306193e-02, -2.2408152e-02],
        [-3.2049812e-02,  1.6736221e-02, -1.8735468e-02, -3.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5504, 1544, 1350, 2400], dtype=int32)

In [16]:
embedded_docs[0].shape

(8,)

In [17]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


array([[[-0.01559485,  0.0080845 ,  0.04357145,  0.03163213,
         -0.04084468, -0.02651745, -0.02663978,  0.00824887,
         -0.02031254, -0.01145422],
        [-0.01559485,  0.0080845 ,  0.04357145,  0.03163213,
         -0.04084468, -0.02651745, -0.02663978,  0.00824887,
         -0.02031254, -0.01145422],
        [-0.01559485,  0.0080845 ,  0.04357145,  0.03163213,
         -0.04084468, -0.02651745, -0.02663978,  0.00824887,
         -0.02031254, -0.01145422],
        [-0.01559485,  0.0080845 ,  0.04357145,  0.03163213,
         -0.04084468, -0.02651745, -0.02663978,  0.00824887,
         -0.02031254, -0.01145422],
        [ 0.04400093,  0.04024967,  0.01645379, -0.01019064,
          0.00045858, -0.0041169 , -0.00458133, -0.01977402,
         -0.04830619, -0.02240815],
        [-0.03204981,  0.01673622, -0.01873547, -0.03493959,
          0.0430265 , -0.02786175,  0.02177921,  0.01084815,
          0.02576392,  0.02308336],
        [ 0.02093129,  0.00117175,  0.04405676, -0.0